export const MarketRiskReasons = {
  VOLATILITY_PANIC: "VOLATILITY_PANIC",
  VOLATILITY_VOLATILE: "VOLATILITY_VOLATILE",
  DIVERGENCE_PANIC: "DIVERGENCE_PANIC",
  DIVERGENCE_VOLATILE: "DIVERGENCE_VOLATILE",
  OUTFLOW_PANIC: "OUTFLOW_PANIC",
  OUTFLOW_VOLATILE: "OUTFLOW_VOLATILE",
  DEPEG_PANIC: "DEPEG_PANIC",
  DEPEG_VOLATILE: "DEPEG_VOLATILE",
  CONFIDENCE_PANIC: "CONFIDENCE_PANIC",
  CONFIDENCE_VOLATILE: "CONFIDENCE_VOLATILE",
  DATA_STALE: "DATA_STALE"
} as const;
