export const YieldRiskReasons = {
  YIELD_STALE: "YIELD_STALE",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  HIGH_EXIT_SLIPPAGE: "HIGH_EXIT_SLIPPAGE",
  SUBSIDY_COLLAPSE_OUTFLOW: "SUBSIDY_COLLAPSE_OUTFLOW",
  APY_DECAYING: "APY_DECAYING",
  HIGH_SUBSIDY_DEPENDENCY: "HIGH_SUBSIDY_DEPENDENCY",
  HIGH_TVL_OUTFLOW: "HIGH_TVL_OUTFLOW",
  LOW_FEE_SUSTAINABILITY: "LOW_FEE_SUSTAINABILITY",
  REWARD_TOKEN_DECAY: "REWARD_TOKEN_DECAY"
} as const;
